micronaut:
  application:
    name: micronautguide
#tag::githubconfig[]
github:
  organization: micronaut-projects
  repo: micronaut-core
  username: micronaut-core
  token: micronaut-core
#end::githubconfig[]